# Generated by Django 5.1.6 on 2025-05-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maderas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
