# Generated by Django 5.1.6 on 2025-05-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maderas', '0004_product_tipomadera_alter_producto_tipo_madera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='wood_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de madera'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
