# Generated by Django 5.1.6 on 2025-05-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maderas', '0005_remove_product_description_product_wood_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('color', models.CharField(default='#45a049', max_length=20)),
            ],
        ),
    ]
