# Generated by Django 5.1.6 on 2025-05-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maderas', '0006_calendarevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]
